homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.41071526670185
  longitude: 2.196155190467835
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: "Europe/Madrid"
  # Customization file
  customize: !include customize.yaml

logger:
  default: debug
  logs:
    homeassistant.components.mqtt: debug
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
      - songpal
      - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

zwave:
  usb_path: /dev/ttyACM0

mqtt:
  broker: 192.168.1.110
  port: 1883
  username: hassio
  password: !secret mqtt_password

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_token
      mac: 78:11:DC:DE:CE:54
      host: 192.168.1.4

hue:
  bridges:
    - host: 192.168.1.2
      allow_unreachable: true
      allow_hue_groups: true

light: !include_dir_merge_list lights/
switch: !include_dir_merge_list switches/
media_player: !include_dir_merge_list media_players/
sensor: !include sensors/sensors.yaml
binary_sensor: !include sensors/binary_sensors.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
timer: !include timers.yaml
# input_datetime: !include_dir_merge_named inputs/dates
input_number: !include_dir_merge_named inputs/numbers
# input_boolean: !include_dir_merge_named inputs/booleans