- alias: Turn on entrance lights at night when motion detected in the entrance
  trigger:
    - platform: mqtt
      topic: aqara/motion/entrance_motion/lux
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.entrance
        state: 'on'
      - condition: template
        value_template: "{{ (trigger.payload | int) < 10 }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.entrance
        brightness: >
          {{ states('input_number.entrance_lights_brightness') | int * 2.55 | round(0) }}
    - service: timer.cancel
      entity_id: timer.entrance_lights_timer
    - service: timer.start
      data_template:
        entity_id: timer.entrance_lights_timer
        duration: >
          {{ states('input_number.entrance_lights_duration') | int | timestamp_custom('%X',false) }}

- alias: Turn off entrance lights when timer expires
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
       entity_id: timer.entrance_lights_timer
  action:
    service: light.turn_off
    entity_id: light.entrance
  
- alias: Dim entrance lights
  trigger:
    platform: state
    entity_id: input_number.entrance_lights_brightness
  condition:
    - condition: state 
      entity_id: light.entrance
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.entrance
        brightness: >
          {{ states('input_number.entrance_lights_brightness') | int * 2.55 | round(0) }}

- alias: Adjust entrance lights brightness
  trigger:
    - platform: state
      entity_id: binary_sensor.is_bedtime
    - platform: homeassistant
      event: start
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.entrance_lights_brightness
        value: >-
          {% if is_state('binary_sensor.is_bedtime', 'on') %}
            10
          {% else %}
            60
          {% endif %}

  