- alias: Turn on entrance lights at night when motion detected in the entrance
  trigger:
    - platform: mqtt
      topic: aqara/motion/entrance_motion/lux
  action:
    - service: script.turn_on_light_with_timer
      data_template:
        entity: light.entrance
        illumination_sensor_id: sensor.illumination_158d0001e0ad52
        brightness_input_id: input_number.entrance_lights_brightness
        duration_input_id: input_number.entrance_lights_duration
        timer_id: timer.entrance_lights_timer

- alias: Turn off entrance lights when timer expires
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
       entity_id: timer.entrance_lights_timer
  action:
    service: light.turn_off
    entity_id: light.entrance
  
- alias: Dim entrance lights
  trigger:
    platform: state
    entity_id: input_number.entrance_lights_brightness
  action:
    service: script.adjust_brightness
    data:
      entity: light.entrance
      brightness_input_id: input_number.entrance_lights_brightness

- alias: Adjust entrance lights brightness
  trigger:
    - platform: state
      entity_id: binary_sensor.is_bedtime
    - platform: homeassistant
      event: start
  action:
    - service: script.day_night_dim
      data:
        brightness_input_id: input_number.entrance_lights_brightness
        day: 70
        night: 10