- alias: Turn on hallway lights when motion detected
  trigger:
    - platform: mqtt
      topic: aqara/motion/hallway_door_motion/status
      payload: motion
    - platform: mqtt
      topic: aqara/motion/entrance_motion/status
      payload: motion
  action:
    - service: python_script.turn_on_light_with_timer
      data_template:
        entity_id: light.hallway
        illumination_sensor_id: sensor.illumination_158d0001e0b206
        brightness_input_id: input_number.hallway_lights_brightness
        duration_input_id: input_number.hallway_lights_duration
        timer_id: timer.hallway_lights_timer

- alias: Turn off hallway lights when timer expires
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
       entity_id: timer.hallway_lights_timer
  action:
    service: light.turn_off
    entity_id: light.hallway
  
- alias: Adjust hallway light brightness
  trigger:
    platform: state
    entity_id: input_number.hallway_lights_brightness
  action:
    service: python_script.adjust_light_brightness
    data:
      entity_id: light.hallway
      brightness_input_id: input_number.hallway_lights_brightness

- alias: Adjust hallway lights brightness
  trigger:
    - platform: state
      entity_id: binary_sensor.is_bedtime
    - platform: homeassistant
      event: start
  action:
    - service: python_script.day_night_light_dim
      data:
        brightness_input_id: input_number.hallway_lights_brightness
        day: 20
        night: 10