- alias: Turn on hallway lights at night or when dark when motion detected in the hallway
  trigger:
    - platform: mqtt
      topic: "aqara/motion/hallway_door_motion/lux"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.hallway
        state: 'on'
      - condition: template
        value_template: "{{ (trigger.payload | int) < 10 }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hallway
        brightness: >
          {{ states('input_number.hallway_lights_brightness') | int * 2.55 | round(0) }}
    - service: timer.cancel
      entity_id: timer.hallway_lights_timer
    - service: timer.start
      entity_id: timer.hallway_lights_timer
      data_template:
        duration: >
          {{ states('input_number.hallway_lights_duration') | int | timestamp_custom('%X',false) }}

- alias: Turn on hallway lights at night or when dark when motion detected at the entrance
  trigger:
    platform: mqtt
    topic: aqara/motion/entrance_motion/lux
    payload: 'motion'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.hallway
        state: 'on'
      - condition: template
        value_template: "{{ (trigger.payload | int) < 10 }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hallway
        brightness: >
          {{ states('input_number.hallway_lights_brightness') | int * 2.55 | round(0) }}
    - service: timer.cancel
      entity_id: timer.hallway_lights_timer
    - service: timer.start
      entity_id: timer.hallway_lights_timer
      data_template:
        duration: >
          {{ states('input_number.hallway_lights_duration') | int | timestamp_custom('%X',false) }}

- alias: Turn off hallway lights when timer expires
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
       entity_id: timer.hallway_lights_timer
  action:
    service: light.turn_off
    entity_id: light.hallway
  
- alias: Adjust hallway light brightness
  trigger:
    platform: state
    entity_id: input_number.hallway_lights_brightness
  condition:
    - condition: state 
      entity_id: light.hallway
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hallway
        brightness: >
          {{ states('input_number.hallway_lights_brightness') | int * 2.55 | round(0) }}

- alias: Adjust hallway lights brightness
  trigger:
    - platform: state
      entity_id: binary_sensor.is_bedtime
    - platform: homeassistant
      event: start
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hallway_lights_brightness
        value: >-
          {% if is_state('binary_sensor.is_bedtime', 'on') %}
            10
          {% else %}
            20
          {% endif %}