- alias: Turn on kitchen lights when motion detected
  trigger:
    - platform: mqtt
      topic: aqara/motion/kitchen_motion/motion
      payload: motion
  action:
    - service: script.turn_on_light_with_timer
      data_template:
        entity: light.kitchen_led_strip
        illumination_sensor_id: sensor.illumination_158d0001e08c62
        brightness_input_id: input_number.kitchen_lights_brightness
        duration_input_id: input_number.kitchen_lights_duration
        timer_id: timer.kitchen_lights_timer

- alias: Turn off kitchen lights when timer expires
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
       entity_id: timer.kitchen_lights_timer
  action:
    service: light.turn_off
    entity_id: light.kitchen_led_strip
  
- alias: Adjust kitchen light brightness
  trigger:
    platform: state
    entity_id: input_number.kitchen_lights_brightness
  action:
    service: script.adjust_brightness
    data:
      entity: light.kitchen_led_strip
      brightness_input_id: input_number.kitchen_lights_brightness

- alias: Adjust kitchen lights brightness
  trigger:
    - platform: state
      entity_id: binary_sensor.is_bedtime
    - platform: homeassistant
      event: start
  action:
    - service: script.day_night_dim
      data:
        brightness_input_id: input_number.kitchen_lights_brightness
        day: 70
        night: 20